# Generated by Django 2.2 on 2021-05-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='no value'),
            preserve_default=False,
        ),
    ]
